export const SHIP_TYPES = Object.freeze({
    Viper: {
        id: 'Viper',
        displayName: 'Viper',
        size: 8.0,
        maxHullStrength: 100,
        thrusterStrength: 100,
        maxThrusterStrength: 100,
        plasmaCannonStrength: 100,
        maxPlasmaCannonStrength: 100,
        maxCapacitor: 100,
        maxShieldStrength: 100,
        shieldRechargeRate: 0.25,
        shieldDecayRate: 0.25,
        reactorOutputPerSecond: 10,
        thrusterEnergyPerSecond: 300,
        laserEnergyCost: 10,
        laserFuelCapacity: 30,
        laserFuelConsumptionRate: 30,
        rotationEnergyPerSecond: 300,
        thrusterForceProduced: 14400000,
        mass: 12000
    },
    Turtle: {
        id: 'Turtle',
        displayName: 'Turtle',
        size: 8.0,
        maxHullStrength: 100,
        thrusterStrength: 100,
        maxThrusterStrength: 100,
        plasmaCannonStrength: 100,
        maxPlasmaCannonStrength: 100,
        maxCapacitor: 100,
        maxShieldStrength: 100,
        shieldRechargeRate: 0.25,
        shieldDecayRate: 0.25,
        reactorOutputPerSecond: 10,
        thrusterEnergyPerSecond: 300,
        laserEnergyCost: 10,
        laserFuelCapacity: 30,
        laserFuelConsumptionRate: 30,
        rotationEnergyPerSecond: 300,
        thrusterForceProduced: 14400000,
        mass: 12000
    }
});

